[tool.black]
force-exclude = '^/scripts|^/alembic|^/venv*|^/livedocs'

[tool.mypy]
python_version = "3.11"
exclude = [
    "^scripts",
    "^alembic",
    "^livedocs",
    "^venv*"
]
show_error_codes = true
disable_error_code = ["override"]
check_untyped_defs = true
no_implicit_optional = true
namespace_packages = true

[[tool.mypy.overrides]]
module = []
ignore_missing_imports = true
no_implicit_optional = false
